plugins:
  - jekyll-remote-theme

remote_theme: ngzhio/jekyll-theme-hamilton

skin: Daylight

- title: Twitter
  url: https://twitter.com/reAlexByk
  icon: fab fa-twitter
- title: GitHub
  url: https://github.com/realexbyk
  icon: fab fa-github
 
 
